 (async()=>{let d=RedDotStore.read();try{const r=await fetch('/api/public/site',{cache:'no-store'});if(r.ok)d=await r.json();}catch(e){console.warn('正在使用本地演示数据',e)}const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  $('#heroTitle').textContent=d.settings.heroTitle;$('#heroSub').textContent=d.settings.heroSub;$('#aboutText').textContent=d.settings.about;$('#footerIntro').textContent=d.settings.footer;$('#contactInfo').innerHTML=`联系人：${esc(d.settings.contact)}<br>电话：${esc(d.settings.phone)}<br>地址：${esc(d.settings.address)}`;
  const capabilityIcons=[
    '<svg viewBox="0 0 48 48"><rect x="13" y="13" width="17" height="17" rx="2"/><path d="M17 9V6m5 3V6m5 3V6m-10 27v3m5-3v3m5-3v3M9 17H6m3 5H6m3 5H6m27-10h3m-3 5h3m-3 5h3"/><circle cx="34" cy="34" r="7"/><path d="m39 39 4 4"/></svg>',
    '<svg viewBox="0 0 48 48"><rect x="7" y="9" width="34" height="29" rx="3"/><path d="M15 18h10M15 24h18M15 30h13M32 15v8m-4-4h8"/></svg>',
    '<svg viewBox="0 0 48 48"><rect x="8" y="8" width="32" height="32" rx="4"/><path d="m20 18-6 6 6 6m8-12 6 6-6 6M25 16l-3 16"/></svg>',
    '<svg viewBox="0 0 48 48"><path d="M17 10h14l5 5v21H12V15l5-5Z"/><path d="M31 10v6h6M18 24l4 4 8-8M18 32h12"/></svg>',
    '<svg viewBox="0 0 48 48"><path d="M8 18h22v16H8zM30 22h6l5 5v7H30z"/><path d="M13 34a4 4 0 1 0 8 0m11 0a4 4 0 1 0 8 0M8 22h22"/><path d="m17 14 5-5 5 5"/></svg>',
    '<svg viewBox="0 0 48 48"><circle cx="14" cy="14" r="5"/><circle cx="34" cy="14" r="5"/><circle cx="24" cy="34" r="5"/><path d="m18 16 11 0m-13 3 5 10m11-10-5 10"/></svg>'
  ];
  $('#capabilities').innerHTML=d.capabilities.map((x,i)=>`<article class="capability capability-${i+1}"><i>${x[0]}</i><span class="capability-icon" aria-hidden="true">${capabilityIcons[i]||capabilityIcons[0]}</span><h3>${esc(x[1])}</h3><p>${esc(x[2])}</p><small>${esc(x[3]||'')}</small></article>`).join('');
  const solutions=d.solutions.filter(x=>x.enabled!==false),news=d.news.filter(x=>x.enabled!==false),platforms=d.platforms.filter(x=>x.enabled!==false);
  const solutionGrid=$('#solutionsGrid'),solutionCarousel=$('#solutionsCarousel'),solutionPrev=$('#solutionPrev'),solutionNext=$('#solutionNext'),solutionsPerPage=6;let solutionPage=0;
  const solutionSource=solutions.map((item,index)=>({item,index})),solutionPages=Math.ceil(solutionSource.length/solutionsPerPage);
  const pageSolutions=page=>{const start=page*solutionsPerPage,items=solutionSource.slice(start,start+solutionsPerPage);if(solutionSource.length<=solutionsPerPage||items.length===solutionsPerPage)return items;const shown=new Set(items.map(entry=>entry.index));for(const entry of solutionSource){if(items.length===solutionsPerPage)break;if(!shown.has(entry.index)){items.push(entry);shown.add(entry.index)}}return items};
  const renderSolutions=()=>{const items=pageSolutions(solutionPage);solutionGrid.innerHTML=items.map(({item:x,index:i})=>`<a class="solution" href="solution.html?id=${encodeURIComponent(x.id||i)}" style="background-image:url('${/^https?:/.test(x.image||'')?x.image:`assets/${x.image||x[2]}`}')"><div><h3>${esc(x.title||x[0])}</h3><p>${esc(x.subtitle||x[1])}</p></div></a>`).join('');solutionCarousel.classList.toggle('has-pages',solutionPages>1);solutionPrev.hidden=solutionNext.hidden=solutionPages<=1};
  solutionPrev.onclick=()=>{solutionPage=(solutionPage-1+solutionPages)%solutionPages;renderSolutions()};solutionNext.onclick=()=>{solutionPage=(solutionPage+1)%solutionPages;renderSolutions()};renderSolutions();
  const groups=Object.entries(platforms.reduce((all,item)=>{(all[item.type||item[1]]??=[]).push(item);return all},{}));
  $('#starMap').classList.add('platform-matrix');
  $('#starMap').innerHTML=`<div class="platform-core"><span>GROUP HUB</span><b>浙江红点创芯科技发展有限公司</b><small>汽车芯片国产化解决方案平台</small></div><div class="platform-lanes">${groups.map(([type,items])=>{const scrollable=items.length>3;return `<section class="platform-lane${scrollable?' has-scroll':''}"><header><i></i><b>${esc(type)}</b><small>${items.length} 家业务主体</small></header><div class="platform-company-viewport"><div class="platform-company-list">${items.map(item=>`<article class="platform-node"><b>${esc(item.name||item[0])}</b><small>${esc(item.comment||item[2])}</small></article>`).join('')}</div></div>${scrollable?'<div class="lane-scrollbar" aria-label="拖动查看全部企业"><span></span></div>':''}</section>`}).join('')}</div>`;
  document.querySelectorAll('.platform-lane.has-scroll').forEach(lane=>{const viewport=lane.querySelector('.platform-company-viewport'),rail=lane.querySelector('.lane-scrollbar'),thumb=rail.querySelector('span');let dragStart=0,startScroll=0;const update=()=>{const max=viewport.scrollHeight-viewport.clientHeight,railHeight=rail.clientHeight,thumbHeight=Math.max(28,railHeight*viewport.clientHeight/viewport.scrollHeight);const top=max?((railHeight-thumbHeight)*viewport.scrollTop/max):0;thumb.style.height=`${thumbHeight}px`;thumb.style.transform=`translateY(${top}px)`};viewport.addEventListener('scroll',update,{passive:true});addEventListener('resize',update);thumb.addEventListener('pointerdown',event=>{dragStart=event.clientY;startScroll=viewport.scrollTop;thumb.setPointerCapture(event.pointerId);event.preventDefault()});thumb.addEventListener('pointermove',event=>{if(!thumb.hasPointerCapture(event.pointerId))return;const max=viewport.scrollHeight-viewport.clientHeight,range=rail.clientHeight-thumb.offsetHeight;viewport.scrollTop=startScroll+(event.clientY-dragStart)*max/range});rail.addEventListener('pointerdown',event=>{if(event.target===thumb)return;const ratio=(event.clientY-rail.getBoundingClientRect().top)/rail.clientHeight;viewport.scrollTop=ratio*(viewport.scrollHeight-viewport.clientHeight)});requestAnimationFrame(update)});
  const homepageNews=[...news].sort((a,b)=>String(b.date||b[2]||'').localeCompare(String(a.date||a[2]||''))).slice(0,3);
  $('#newsGrid').innerHTML=homepageNews.map((x,i)=>`<a class="news-card" href="news-detail.html?id=${encodeURIComponent(x.id||i)}"><div class="news-thumb" style="background-image:url('${/^https?:/.test(x.image||'')?x.image:`assets/${x.image||x[3]}`}')"></div><div class="news-body"><small>${esc(x.category||x[0])}</small><h3>${esc(x.title||x[1])}</h3><time>${esc(x.date||x[2])}</time></div></a>`).join('');
  const header=$('#siteHeader'),hero=$('#hero'),syncHeader=()=>header.classList.toggle('scrolled',window.scrollY>=hero.offsetHeight-header.offsetHeight);addEventListener('scroll',syncHeader,{passive:true});addEventListener('resize',syncHeader);syncHeader();requestAnimationFrame(()=>hero.classList.add('is-ready'));const toggle=$('.menu-toggle'),nav=$('.site-header nav');toggle.onclick=()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open)};
  const motionTargets=document.querySelectorAll('.home-page main > .section,.home-page main > .enterprise-mission,.home-page main > .cta-band');
  if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&'IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.14});motionTargets.forEach(item=>{item.classList.add('reveal');observer.observe(item)})}else motionTargets.forEach(item=>item.classList.add('is-visible'));
})();
