(async()=>{
  try{
    const site=await fetch('/api/public/site',{cache:'no-store'}).then(response=>response.json());
    const companies=(site.distribution||[]).flatMap(city=>(city.companies||[]).map(company=>({name:company.name||company[0],type:company.type||company[1],description:company.description||company.comment||'',city:city.name,attribute:company.attribute||'子公司'})));
    const group=companies.find(company=>company.attribute==='集团')||companies[0];
    const children=companies.filter(company=>company!==group);const root=document.querySelector('#starMap');if(!root||!group)return;
    root.className='star-map group-cosmos';root.innerHTML=`<canvas class="cosmos-canvas" aria-hidden="true"></canvas><div class="cosmos-glow" aria-hidden="true"></div><div class="cosmos-group"><span>GROUP COMPANY</span><b>${group.name}</b><p>${group.description||group.type}</p></div><div class="cosmos-stage"><div class="cosmos-axis"></div>${children.map((company,index)=>{const angle=(360/Math.max(children.length,1))*index-90,depth=(Math.sin(angle*Math.PI/180)+1)/2;return `<article class="cosmos-company" style="--angle:${angle}deg;--depth:${.78+depth*.22};--lift:${-24+depth*48}px"><span class="company-type">${company.type}</span><b>${company.name}</b><p>${company.description||`${company.city} · ${company.type}`}</p><i>⌁</i></article>`}).join('')}</div><p class="cosmos-hint">悬停子公司，查看企业信息</p>`;
    const stage=root.querySelector('.cosmos-stage'),cards=[...root.querySelectorAll('.cosmos-company')];cards.forEach(card=>{const activate=()=>{cards.forEach(other=>other.classList.remove('is-active'));card.classList.add('is-active');stage.classList.add('has-active')},clear=()=>{card.classList.remove('is-active');stage.classList.remove('has-active')};card.addEventListener('mouseenter',activate);card.addEventListener('mouseleave',clear);card.addEventListener('focus',activate);card.addEventListener('blur',clear);card.tabIndex=0});
    const canvas=root.querySelector('.cosmos-canvas'),context=canvas.getContext('2d');let width=0,height=0,stars=[];const resize=()=>{const ratio=Math.min(devicePixelRatio||1,2);width=canvas.clientWidth;height=canvas.clientHeight;canvas.width=width*ratio;canvas.height=height*ratio;context.setTransform(ratio,0,0,ratio,0,0);stars=Array.from({length:Math.max(85,Math.floor(width*height/9000))},()=>({x:Math.random()*width,y:Math.random()*height,r:Math.random()*1.2+.25,s:Math.random()*.18+.03,a:Math.random()*.7+.15}))};const draw=()=>{context.clearRect(0,0,width,height);for(const star of stars){star.x-=star.s;if(star.x<0)star.x=width;context.beginPath();context.fillStyle=`rgba(255,235,237,${star.a})`;context.arc(star.x,star.y,star.r,0,Math.PI*2);context.fill()}requestAnimationFrame(draw)};new ResizeObserver(resize).observe(root);resize();draw();
  }catch(error){console.warn('集团星空图加载失败，将保留默认展示。',error)}
})();
